<?php
/**
 * Created by PhpStorm.
 * User: lenovo
 * Date: 2017/10/25
 * Time: 13:31
 */
return array(
    'email' => array(
        'smtphost' => 'smtp.exmail.qq.com',
        'smtpport' => '25',
        'smtpuser' => '',   //发信者的邮箱
        'smtppass' => '',   //邮箱密码
    ),
    'security' => array(   //安全参数
        'pwdModificationTime' => '30',  //密码最长修改时间
    ),
    'uploaddir' => 'uploads',   //配置上传目录
    'pwdModificationTime' => '30',
    //允许添加的角色
    'allowaddroles' => array(
        'BG', 'koFranchiseCl', 'koMDM', 'koOtherBU', 'koProjectTeam', 'OU'
    ),
    //上传zip文件
//         'uploadZip'=>'./uploads/' . date_default_timezone_set("Asia/Shanghai") . '/zip/',
    'uploadZip' => './uploads/' . date("Y-m") . '/zip/',
    'zip_type' => array('application/x-zip', 'application/zip', 'application/x-zip-compressed', 'application/octet-stream'),
    'zip_or_excel' => array('application/x-zip', 'application/zip', 'application/x-zip-compressed', 'application/octet-stream', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'),
    'excelSuffix' => '.xlsx',
    'zip_max_size' => '500000000',//100M
    //全部城市可以下载的角色
    /* 'allcitydownloadrole'=>array(
         'koProjectTeam'
     )*/
    'cvs_map_china' => array(
        'China' => '全国',
        'All' => '全部',
        'Zhuhai' => '珠海',
        'SBL' => '太古',
        'CBL' => '中可',
        'Bottler' => '装瓶厂',
        'Beijing' => '北京',
        'Gansu' => '甘肃',
        'Hebei' => '河北',
        'Heilongjiang' => '黑龙江',
        'Hunan' => '湖南',
        'Jilin' => '吉林',
        'Liaoning' => '辽宁',
        'Inner Mongolia' => '内蒙古',
        'Shandong' => '山东',
        'Shanxi' => '山西',
        'Shannxi' => '陕西',
        'Sichuan' => '四川',
        'Tianjin' => '天津',
        'Xinjiang' => '新疆',
        'Chongqing' => '重庆',
        'Anhui' => '安徽',
        'Fujian' => '福建',
        'Guangxi' => '广西',
        'Yuexi' => '粤西',
        'Hainan' => '海南',
        'Henan' => '河南',
        'Hubei' => '湖北',
        'Jiangsu' => '江苏',
        'Jiangxi' => '江西',
        'Shenmei' => '申美',
        'Yuedong' => '粤东',
        'Yunnan' => '云南',
        'Zhejiang' => '浙江',
        'ZhanMao' => '湛茂',
        'Lanzhou' => '兰州',
        'Yinchuan' => '银川',
        'Shijiazhuang' => '石家庄',
        'Tangshan' => '唐山',
        'Harbin' => '哈尔滨',
        'Changsha' => '长沙',
        'Guiyang' => '贵阳',
        'Changchun' => '长春',
        'Dalian' => '大连',
        'Shenyang' => '沈阳',
        'Anshan' => '鞍山',
        'Hohhot' => '呼和浩特',
        'Qingdao' => '青岛',
        'Ji\'nan' => '济南',
        'Weifang' => '潍坊',
        'Yantai' => '烟台',
        'Taiyuan' => '太原',
        'Xi\'an' => '西安',
        'Chengdu' => '成都',
        'Urumchi' => '乌鲁木齐',
        'Hefei' => '合肥',
        'Fuzhou' => '福州',
        'Xiamen' => '厦门',
        'Quanzhou' => '泉州',
        'Nanning' => '南宁',
        'Guangzhou' => '广州',
        'Foshan' => '佛山',
        'Haikou' => '海口',
        'Sanya' => '三亚',
        'Zhengzhou' => '郑州',
        'Wuhan' => '武汉',
        'Xiangyang' => '襄阳',
        'Nanjing' => '南京',
        'Changzhou' => '常州',
        'Yangzhou' => '扬州',
        'Nanchang' => '南昌',
        'Shanghai' => '上海',
        'Nantong' => '南通',
        'Suzhou' => '苏州',
        'Wuxi' => '无锡',
        'Shenzhen' => '深圳',
        'Dongguan' => '东莞',
        'Huizhou' => '惠州',
        'Kunming' => '昆明',
        'Hangzhou' => '杭州',
        'Ningbo' => '宁波',
        'Wenzhou' => '温州',
        'Zhanjiang' => '湛江',
        'Luoyang' => '洛阳',
        'Putian'=>'莆田',
    ),
    'map_china' => array(
        '全国' => 'China',
        '全部' => 'Bottling Group',
        '珠海' => 'Zhuhai',
        '太古' => 'SBL',
        '中可' => 'CBL',
        '装瓶厂' => 'OU',
        '北京' => 'Beijing',
        '甘肃' => 'Gansu',
        '河北' => 'Hebei',
        '黑龙江' => 'Heilongjiang',
        '湖南' => 'Hunan',
        '吉林' => 'Jilin',
        '辽宁' => 'Liaoning',
        '内蒙古' => 'Inner Mongolia',
        '山东' => 'Shandong',
        '山西' => 'Shanxi',
        '陕西' => 'Shannxi',
        '四川' => 'Sichuan',
        '天津' => 'Tianjin',
        '新疆' => 'Xinjiang',
        '重庆' => 'Chongqing',
        '安徽' => 'Anhui',
        '福建' => 'Fujian',
        '广西' => 'Guangxi',
        '粤西' => 'Yuexi',
        '海南' => 'Hainan',
        '河南' => 'Henan',
        '湖北' => 'Hubei',
        '江苏' => 'Jiangsu',
        '江西' => 'Jiangxi',
        '申美' => 'Shenmei',
        '粤东' => 'Yuedong',
        '云南' => 'Yunnan',
        '浙江' => 'Zhejiang',
        '湛茂' => 'ZhanMao',
        '城市' => 'City',
        '兰州' => 'Lanzhou',
        '银川' => 'Yinchuan',
        '石家庄' => 'Shijiazhuang',
        '唐山' => 'Tangshan',
        '哈尔滨' => 'Harbin',
        '长沙' => 'Changsha',
        '贵阳' => 'Guiyang',
        '长春' => 'Changchun',
        '大连' => 'Dalian',
        '沈阳' => 'Shenyang',
        '鞍山' => 'Anshan',
        '呼和浩特' => 'Huhehaote',
        '青岛' => 'Qingdao',
        '济南' => 'Ji\'nan',
        '潍坊' => 'Weifang',
        '烟台' => 'Yantai',
        '太原' => 'Taiyuan',
        '西安' => 'Xi\'an',
        '成都' => 'Chengdu',
        '乌鲁木齐' => 'Wulumuqi',
        '合肥' => 'Hefei',
        '福州' => 'Fuzhou',
        '厦门' => 'Xiamen',
        '泉州' => 'Quanzhou',
        '南宁' => 'Nanning',
        '广州' => 'Guangzhou',
        '佛山' => 'Foshan',
        '海口' => 'Haikou',
        '三亚' => 'Sanya',
        '郑州' => 'Zhengzhou',
        '武汉' => 'Wuhan',
        '襄阳' => 'Xiangyang',
        '南京' => 'Nanjing',
        '常州' => 'Changzhou',
        '扬州' => 'Yangzhou',
        '南昌' => 'Nanchang',
        '上海' => 'Shanghai',
        '南通' => 'Nantong',
        '苏州' => 'Suzhou',
        '无锡' => 'Wuxi',
        '深圳' => 'Shenzhen',
        '东莞' => 'Dongguan',
        '惠州' => 'Huizhou',
        '昆明' => 'Kunming',
        '杭州' => 'Hangzhou',
        '宁波' => 'Ningbo',
        '温州' => 'Wenzhou',
        '湛江' => 'Zhanjiang',
        '洛阳' => 'Luoyang',
        '北区' => 'BeiQu',
        '杨浦' => 'YangPu',
        '长宁' => 'ChangNing',
        '黄浦' => 'HuangPu',
        '上南' => 'ShangNan',
        '南汇' => 'NanHui',
        '宝山' => 'BaoShan',
        '松江' => 'SongJiang',
        '闵行' => 'MinHang',
        '浦东' => 'PuDong',
        '青浦' => 'QingPu',
        '奉贤&金山' => 'FengXiang&JinShan',
        '虹口' => 'HongKou',
        '嘉定' => 'JiaDing',
        '川沙' => 'ChuanSha',
        '崇明' => 'ChongMing',
        '莆田'=>'Putian',

    ),
    'shelves' => array(
        '0' => '',
        '1' => '常温+冷藏+暖柜',
        '2' => '常温',
        '3' => '冷藏',
        '4' => '暖柜',
    ),
    'activity' => array(
        '0' => '',
        '1' => '圣诞节',
        '2' => '北极熊',
    ),
    'mechanism' => array(
        '0' => '',
        '1' => '套餐',
        '2' => 'N件X折',
        '3' => '会员',
        '4' => '赠品',
        '5' => '特价',
    ),
    'equipment' => array(
        '0' => '',
        '1' => '咖啡机',
        '2' => '冰柜',
        '3' => '暖柜',
        '4' => '总设备',
    ),
    'cache' => array(
        'cvsdatatime' => 3600 * 24,
        'retaildatatime' => 3600 * 24
    ),
    'at'=>array(
        'url'=>"https://fedloginuat.icoke.cn:8081/",//测试环境:https://fedloginuat.icoke.cn:8081/。正式环境:https://fedlogin.icoke.cn:8081/
        'client_id'=>'10',//测试环境：10，正式环境：7
        'client_secret'=>'vwgmp8ersar4'//测试环境:vwgmp8ersar4。正式环境：pjzik9s9ejn2
    ),
    //是否启用KO集成登陆
    'kologin' => false,
    'ziplabel' => [
        '地图' => 'map',
        '仪表盘' => 'dashboard',
        '图表' => 'chart',
        '配售率比较1' => 'comparison_of_attach_rate1',
        '配售率比较2' => 'comparison_of_attach_rate2',
        '配售率趋势' => 'trend_of_attach_rate',
        '可见率比较1' => 'comparison_of_availability1',
        '可见率比较2' => 'comparison_of_availability2',
        '可见率趋势' => 'trend_of_availability',
        '点购率比较1' => 'comparison_of_incidence1',
        '点购率比较2' => 'comparison_of_incidence2',
        '点购率趋势' => 'trend_of_incidence',
        '订单数量比较1' => 'comparison_of_orders1',
        '订单数量比较2' => 'comparison_of_orders2',
        '订单数量趋势' => 'trend_of_orders',
        '门店数量比较1' => 'comparison_of_outlet_number1',
        '门店数量比较2' => 'comparison_of_outlet_number2',
        '门店数量趋势' => 'trend_of_outlet_number',
        '店均点购门店数量比较1' => 'comparison_of_OPO1',
        '店均点购门店数量比较2' => 'comparison_of_OPO2',
        '店均点购门店数量趋势' => 'trend_of_OPO',
        '配售率' => 'attach_rate',
        '可见率' => 'availability',
        '点购率' => 'incidence',
        '概况' => 'overview',
        '铺货率' => 'Availability',
        'SOVI' => 'SOVI',
        '活动发生率' => 'Activation',
        '设备卖进率' => 'Equipment',
        '零售价格' => 'Retail_price',
        '铺货率比较2' => 'Availability_Compare2',
        '铺货网店比较2' => 'Store_Compare2',
        'SOVI比较2' => 'SOVI Compare2',
        '活动发生率比较2' => 'Activation2',
        '设备卖进率比较2' => 'Equipment2',
        '店均货架排面数比较2' => 'AVG_face2',
        '零售价格店次占比比较2' => 'Retail_price_R2',
        '促销店次占比比较2' => 'Promotion_R2',

        '铺货率比较1' => 'Availability_Compare1',
        '铺货网店比较1' => 'Store_Compare1',
        'SOVI比较1' => 'SOVI Compare1',
        '活动发生率比较1' => 'Activation1',
        '设备卖进率比较1' => 'Equipment1',
        '店均货架排面数比较1' => 'AVG_face1',
        '零售价格店次占比比较1' => 'Retail_price_R1',
        '促销店次占比比较1' => 'Promotion_R1',

        '设备卖进率趋势' => 'Equipment_Trend',
        '铺货率趋势' => 'Availability_Trend',
        '铺货网店趋势' => 'Store_Trend',
        'SOVI趋势' => 'SOVI_Trend',
        '店均货架排面数趋势' => 'AVG_face_Trend',
        '零售价格店次占比趋势' => 'Retail_price_R_Trend',
        '活动发生率趋势' => 'Activation_Trend',
        '促销店次占比趋势' => 'Promotion_R_Trend',
    ],
    'statistics' => [
        'distribution' => '铺货率',
        'sovi' => '排面占比',
        'thematic_activity' => '活动发生率',
        'promotion' => '促销店次占比',
        'equipment_sales' => '设备卖进率',
        'distribution_stores' => '铺货网店数',
        'shelf_number' => '店均货架排面数',
        'extra_displays' => '额外二次陈列',
        'extra_stores' => '二次陈列门店数',
        'freezer_shop' => '可口可乐暖柜店均门数',
        'Last_distribution_radio' => '铺货率的变化率',
        'Last_sovi_radio' => '排面占比的变化率',
        'Last_thematic_activity_radio' => '活动发生率的变化率',
        'Last_promotion_radio' => '促销店次占比的变化率',
        'Last_equipment_sales_radio' => '设备卖进率的变化率',
        'Last_distribution_stores_radio' => '铺货网店数量的变化率',
        'Last_shelf_number_radio' => '店均货架排面数的变化率',
        'Last_extra_displays_radio' => '额外二次陈列的变化率',
        'Last_extra_stores' => '二次陈列门店数的变化率',
        'Last_freezer_shop' => '可口可乐暖柜店均门数的变化率'
    ],
    'specialLocate' => [ //特殊地点的经纬度设置
        '全部' => '107.764827,36.104582',
        '全国' => '107.764827,36.104582',
        '太古' => '117.720126,30.896448',
        '粤西' => '112.02872,23.557816',
        '粤东' => '116.02872,23.557816',
        '申美' => '120.554599,31.422918',
        '上海' => '120.554599,31.422918',
        '中可' => '109.897861,37.608898',
        '珠海' => '120.554599,31.422918',
    ],
    'eng_specialLocate' => [ //特殊地点的经纬度设置
        'BG' => '107.764827,36.104582',
        'China' => '107.764827,36.104582',
        'All' => '107.764827,36.104582',
        'SBL' => '117.720126,30.896448',
        'Yuexi' => '112.02872,23.557816',
        'Yuedong' => '116.02872,23.557816',
        'Shenmei' => '120.554599,31.422918',
        'Shanghai' => '120.554599,31.422918',
        'CBL' => '109.897861,37.608898',
        'ZH' =>'120.554599,31.422918',
    ],
    'classify' => [
        1 => ["常温货架数", 'red'],
        2 => ["端架数", '#477ED9'],
    ],
    'sku'=>[
        1=>'品类',
        2=>'制造商',
        3=>'品牌',
        4=>'系列',
    ],
    'sku_classify'=>[
        '1'=>"KO",
        '2'=>"竞品",
        '3'=>'NARTD'
    ],
    'bottle_grade'=>[
        '1'=>'箱装',
        '2'=>'单瓶装',
        '3'=>'多瓶装',
    ],
    'capacity_grade'=>[
        '1'=>'SSS(0-400ml)',
        '2'=>'SS(401-800ml)',
        '3'=>'SMS(801-1250ml)',
        '4'=>'MS(1251-2000ml)',
        '5'=>'LMS(2001-3000ml)',
        '6'=>'BULK(3L and above)',
    ],
    'puzzle'=>[
        'saleroom'=>'销售金额',
        'last_saleroom'=>'销售金额的变化率',
        'sales_numbers'=>'销售件数',
        'last_sales_numbers'=>'销售件数的变化率',
        'sales_share'=>'销售金额占比',
        'sales_quota'=>'销售件数占比',
        'last_sales_share'=>'销售金额占比',
        'last_sales_quota'=>'销售件数占比',
        'average_discount_factor'=>'折扣深度',
        'last_average_discount_factor'=>'折扣深度的变化率',
        'price_promotion_ratio'=>'价格促销渗透率',
        'last_price_promotion_ratio'=>'价格促销渗透率的变化率',
    ],
    'kpichecked' => [
        1 => ['current' => 'distribution', 'gradient' => 'last_distribution'],//铺货率
        2 => ['current' => 'sales_numbers', 'gradient' => 'last_sales_numbers'],//销售件数
        3 => ['current' => 'sales_quota', 'gradient' => 'last_sales_quota'],//销售件数占比
        4 => ['current' => 'saleroom', 'gradient' => 'last_saleroom'],//销售金额
        5 => ['current' => 'sales_share', 'gradient' => 'last_sales_share'],//销售金额占比
        6 => ['current' => 'enrollment', 'gradient' => 'last_enrollment'],//上线率
        7 => ['current' => 'store_money', 'gradient' => 'last_store_money'],//单店产出金额
        8 => ['current' => 'store_number', 'gradient' => 'last_store_number'],//单店产出件数
        9 => ['current' => 'sku_number', 'gradient' => 'last_sku_number'],//sku数
        10 => ['current' => 'distribution_store', 'gradient' => 'last_distribution_store'],//铺货网店数
        11 => ['current' => 'average_selling_price', 'gradient' => 'last_average_selling_price'],//平均售价
        12 => ['current' => 'average_purchase_price', 'gradient' => 'last_average_purchase_price'],//平均购买价
        13 => ['current' => 'price_promotion_ratio', 'gradient' => 'last_price_promotion_ratio'],//价格促销渗透率
        14 => ['current' => 'average_discount_factor', 'gradient' => 'last_average_discount_factor'],//平均价格深度
        15 => ['current' => 'average_number_per_unit', 'gradient' => 'last_average_number_per_unit'],//平均每单件数
        16 => ['current' => 'average_amount_per_order', 'gradient' => 'last_average_amount_per_order'],//平均每单金额
        17 => ['current' => 'online_stores', 'gradient' => 'last_online_stores'],//上线门店数
    ],
    'defaultTable'=>"cola_info_2018_11_0",
    'defaultTable1'=>"cola_rank_2018_11_0"
);